// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.VBox vbox2;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Label label1;
    
    private Gtk.Entry txturl;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Label label2;
    
    private Gtk.Entry txtname;
    
    private Gtk.VBox vbox3;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Label label3;
    
    private Gtk.FileChooserButton txtpath;
    
    private Gtk.HBox hbox4;
    
    private Gtk.HBox hbox5;
    
    private Gtk.CheckButton chkflv;
    
    private Gtk.CheckButton chkavi;
    
    private Gtk.HBox hbox6;
    
    private Gtk.CheckButton chk3gp;
    
    private Gtk.CheckButton chkmp3;
    
    private Gtk.HBox hbox7;
    
    private Gtk.HSeparator hseparator1;
    
    private Gtk.Label lblstatus;
    
    private Gtk.HBox hbox8;
    
    private Gtk.Button btnok;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Youtube Video Downloader");
        this.Icon = Stetic.IconLoader.LoadIcon(this, "stock_score-highest", Gtk.IconSize.Menu, 16);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.Resizable = false;
        this.AllowGrow = false;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Youtube URL");
        this.hbox1.Add(this.label1);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.txturl = new Gtk.Entry();
        this.txturl.CanFocus = true;
        this.txturl.Name = "txturl";
        this.txturl.IsEditable = true;
        this.txturl.InvisibleChar = '●';
        this.hbox1.Add(this.txturl);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.txturl]));
        w2.Position = 1;
        this.vbox2.Add(this.hbox1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Video Name");
        this.hbox2.Add(this.label2);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.label2]));
        w4.Position = 0;
        w4.Expand = false;
        w4.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.txtname = new Gtk.Entry();
        this.txtname.CanFocus = true;
        this.txtname.Name = "txtname";
        this.txtname.IsEditable = true;
        this.txtname.InvisibleChar = '●';
        this.hbox2.Add(this.txtname);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.txtname]));
        w5.Position = 1;
        this.vbox2.Add(this.hbox2);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        this.vbox1.Add(this.vbox2);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
        w7.Position = 0;
        w7.Expand = false;
        w7.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Destination Folder");
        this.hbox3.Add(this.label3);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox3[this.label3]));
        w8.Position = 0;
        w8.Expand = false;
        w8.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.txtpath = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Please select the destination folder"), ((Gtk.FileChooserAction)(2)));
        this.txtpath.Name = "txtpath";
        this.txtpath.ShowHidden = true;
        this.hbox3.Add(this.txtpath);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox3[this.txtpath]));
        w9.Position = 1;
        this.vbox3.Add(this.hbox3);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
        w10.Position = 0;
        w10.Expand = false;
        w10.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 6;
        // Container child hbox4.Gtk.Box+BoxChild
        this.hbox5 = new Gtk.HBox();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 6;
        // Container child hbox5.Gtk.Box+BoxChild
        this.chkflv = new Gtk.CheckButton();
        this.chkflv.CanFocus = true;
        this.chkflv.Name = "chkflv";
        this.chkflv.Label = Mono.Unix.Catalog.GetString("flv");
        this.chkflv.Active = true;
        this.chkflv.DrawIndicator = true;
        this.chkflv.UseUnderline = true;
        this.hbox5.Add(this.chkflv);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox5[this.chkflv]));
        w11.Position = 0;
        // Container child hbox5.Gtk.Box+BoxChild
        this.chkavi = new Gtk.CheckButton();
        this.chkavi.CanFocus = true;
        this.chkavi.Name = "chkavi";
        this.chkavi.Label = Mono.Unix.Catalog.GetString("avi");
        this.chkavi.DrawIndicator = true;
        this.chkavi.UseUnderline = true;
        this.hbox5.Add(this.chkavi);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox5[this.chkavi]));
        w12.Position = 1;
        this.hbox4.Add(this.hbox5);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox4[this.hbox5]));
        w13.Position = 0;
        // Container child hbox4.Gtk.Box+BoxChild
        this.hbox6 = new Gtk.HBox();
        this.hbox6.Name = "hbox6";
        this.hbox6.Spacing = 6;
        // Container child hbox6.Gtk.Box+BoxChild
        this.chk3gp = new Gtk.CheckButton();
        this.chk3gp.CanFocus = true;
        this.chk3gp.Name = "chk3gp";
        this.chk3gp.Label = Mono.Unix.Catalog.GetString("3gp");
        this.chk3gp.DrawIndicator = true;
        this.chk3gp.UseUnderline = true;
        this.hbox6.Add(this.chk3gp);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox6[this.chk3gp]));
        w14.Position = 0;
        // Container child hbox6.Gtk.Box+BoxChild
        this.chkmp3 = new Gtk.CheckButton();
        this.chkmp3.CanFocus = true;
        this.chkmp3.Name = "chkmp3";
        this.chkmp3.Label = Mono.Unix.Catalog.GetString("mp3");
        this.chkmp3.DrawIndicator = true;
        this.chkmp3.UseUnderline = true;
        this.hbox6.Add(this.chkmp3);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox6[this.chkmp3]));
        w15.Position = 1;
        this.hbox4.Add(this.hbox6);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox4[this.hbox6]));
        w16.Position = 1;
        this.vbox3.Add(this.hbox4);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
        w17.Position = 1;
        w17.Expand = false;
        w17.Fill = false;
        this.vbox1.Add(this.vbox3);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
        w18.Position = 1;
        w18.Expand = false;
        w18.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox7 = new Gtk.HBox();
        this.hbox7.Name = "hbox7";
        this.hbox7.Spacing = 6;
        // Container child hbox7.Gtk.Box+BoxChild
        this.hseparator1 = new Gtk.HSeparator();
        this.hseparator1.Name = "hseparator1";
        this.hbox7.Add(this.hseparator1);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.hbox7[this.hseparator1]));
        w19.Position = 0;
        // Container child hbox7.Gtk.Box+BoxChild
        this.lblstatus = new Gtk.Label();
        this.lblstatus.Name = "lblstatus";
        this.lblstatus.LabelProp = "";
        this.hbox7.Add(this.lblstatus);
        Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox7[this.lblstatus]));
        w20.Position = 1;
        w20.Expand = false;
        w20.Fill = false;
        // Container child hbox7.Gtk.Box+BoxChild
        this.hbox8 = new Gtk.HBox();
        this.hbox8.Name = "hbox8";
        this.hbox8.Spacing = 6;
        // Container child hbox8.Gtk.Box+BoxChild
        this.btnok = new Gtk.Button();
        this.btnok.CanFocus = true;
        this.btnok.Name = "btnok";
        this.btnok.UseUnderline = true;
        this.btnok.Label = Mono.Unix.Catalog.GetString("OK");
        this.hbox8.Add(this.btnok);
        Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox8[this.btnok]));
        w21.Position = 0;
        w21.Expand = false;
        w21.Fill = false;
        this.hbox7.Add(this.hbox8);
        Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox7[this.hbox8]));
        w22.Position = 2;
        w22.Expand = false;
        w22.Fill = false;
        this.vbox1.Add(this.hbox7);
        Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox7]));
        w23.Position = 2;
        w23.Expand = false;
        w23.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 395;
        this.DefaultHeight = 169;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.btnok.Clicked += new System.EventHandler(this.OnBtnokClicked);
    }
}
